- gulpfile.js
- static/robots.txt
add hostname (fixes #137); add sitemap to robots.txt
> sitemap hostname

- templates/updates.html
use metalsmith-pagination helper variables
fixes bad older/newer links when at the first/last page of updates
> improve pager links

- content/markdown/2015-statewide-orthoimagery-project.md
Pull request for ortho project status updates for week ending Jan 23rd. Will email status map.
> Project status updates for week ending Jan 23rd

- content/markdown/news/2015-01-09-naip-2014-statewide-aerial-available.md
Added this note per request from RMitchell.
> Added special note for 2014 coverage

- scss/partials/_base.scss
> add min-height to address to fix copyright on sm screen

- content/markdown/2015-statewide-orthoimagery-project.md
Weekly project activity update.
> ortho-update-feb-6

- content/markdown/2015-statewide-orthoimagery-project.md
Updated project activity and edited leaf-off leaf-on graphic description.
> ortho-update-feb-20

- content/markdown/2015-statewide-orthoimagery-project.md
Updating project activity date.
> ortho-date-update

- templates/order-form.html
> add some more info about the hard drive options to order form

- scss/data-download.scss
- static/js/data-download/app.js
- static/js/data-download/filters/titleizeFilter.js
- static/js/data-download/partials/results.html
- templates/base.html
- templates/data-download.html
- templates/partials/header.html
- Set `title` dynamically
- Better headings that include the selected area and category (like "Travis County")
- Better descriptive text
> SEO changes for Data Download

- static/js/data-download/app.js
> htmlReady method for phantomjs rendering

- content/markdown/2015-statewide-orthoimagery-project.md
> ortho-update-feb-27

- content/markdown/2015-statewide-orthoimagery-project.md
Orthoimagery weekly project update.
> ortho-update-mar-13

- content/markdown/texas-google-imagery.md
Corrected spelling and some grammar on the page
> Google-Imagery-FDRedittext

- content/markdown/texas-google-imagery.md
> google-imagery-edits-mar20

- templates/partials/gio-meeting.html
> Changing meeting room address

- templates/partials/google-request-form.html
> add Organization to google request form

- templates/partials/google-contact.html
Changing text - omit "response time" and change button options for type of contact.
> GoogleContact-edittext-FDR

- content/markdown/2015-statewide-orthoimagery-project.md
> ortho-update-mar-27

- templates/partials/google-update.html
Added end of the month updates; added shapefile for download. Good to go.
> GPUpdates_FDR_20150330

- content/markdown/training.md
also clarify/simplify some language
> fix hanging hyphen

- content/markdown/news/2015-01-09-naip-2014-statewide-aerial-available.md
Changed from April to May for availability of DOQQs.
> naip14-doqq-date-change

- static/js/data-download/directives/resourceGroup.js
- static/js/data-download/partials/resourceGroup.html
the data-download app provides full urls now
> don't prefix download urls

- content/markdown/2015-statewide-orthoimagery-project.md
Weekly project update plus one edit to Color Infrared.
> Ortho update apr 17

- templates/_form_macros.html
ref upstream bug https://github.com/danialfarid/ng-file-upload/issues/682
> predefine window.FileAPI

- templates/partials/google/google-request-form.html
Changed contractor question, removed Part 3 - request for JP2 files
> Changes to Request a Link Form

- templates/partials/highlights.html
> fixing front page forum link

- static/js/data-download/app.js
in the way datasets are categorized
> change way statewide dataset columns are grouped to account for changes

- content/markdown/geographic-information-office/2015-05-14-gis-community-meeting-recap-2nd-quarter-2015.md
> fix link to NAIP 2014 article from GIO community recap article

- gulpfile.js
- package.json
is installable
see https://github.com/ExtraHop/metalsmith-sitemap/issues/7 for details
> drop sitemap generation temporarily until the metalsmith-sitemap package

- .eslintrc
- .jshintrc
- static/js/data-download/app.js
- static/js/data-download/controllers/dataDownloadCtrl.js
- static/js/data-download/directives/downloadMap.js
- static/js/data-download/directives/mapControl.js
- static/js/data-download/directives/resourceGroup.js
- static/js/data-download/filters/titleizeFilter.js
misc fixes, mostly linting for consistent style
> data download code cleanup

- scss/data-download.scss
- static/js/data-download/partials/downloadMap.html
- static/js/site.js
> use {cursor: pointer} when hovering over a clickable item on the map

- static/js/data-download/app.js
- static/js/data-download/services/BrowserService.js
- static/js/data-download/services/CartoService.js
- templates/base.html
- templates/data-download.html
> Ie9 data download jsonp fix

- scss/data-download.scss
so borders are clear of the info and attribution overlays
> bump data download map height slightly

- content/markdown/2015-statewide-orthoimagery-project.md
Weekly report and maps emailed to Chris.
> Ortho update jul 17

- templates/_form_macros.html
> fix checkbox option names when array (different label name) is used

- content/markdown/news/2015-08-11-lidar-data-release-austin-capcog-2012.md
Corrected typo that was caused by my dependency on auto-correct.
> typo corrections

- gulpfile.js
- templates/_macros.html
(e.g. link validation fails because a catalog entry has changed)
> correctly display source file when a data card references a missing card

- content/markdown/news/2013-12-06-lidar-data-release-north-central-texas.md
- content/markdown/news/2015-05-12-central-texas-fort-bend-county-lidar.md
- content/markdown/news/2015-05-19-lidar-release-northeast-texas.md
- content/markdown/news/2015-08-03-lidar-data-release-for-georgetown-texas.md
- content/markdown/news/2015-08-11-lidar-data-release-austin-capcog-2012.md
> fixing Lidar typos in news articles

- templates/partials/google/google-update.html
> removing google shapefile

- content/markdown/order-data.md
quote language and turn around time added
> Orderform edit

- scss/partials/_2015-forum.scss
- templates/partials/2015-forum/forum-nav-2015.html
Fixed PR. Adding active class and styling to currently active nav link.
> add active class and styling to forum nav

- content/markdown/2015-gis-forum.md
- scss/partials/_2015-forum.scss
- static/js/2015forum.js
Because the embedded twitter browser doesn't support localStorage, so some weird behavior happens.
> Check for localStorage support before adding starring functionality

- static/js/data-download/services/DataService.js
- static/js/data-download/services/MapService.js
> Fix quad quotes

- templates/_form_macros.html
- templates/order-form.html
- Only show full Order Data form once "Type of Data" is selected
- Hide the form and show a success message on any successfully submitted form
> Form improvements

- content/markdown/contact.md
- templates/contact.html
> simplify contact form

- templates/order-form.html
deploy to be sync'd with a change to Google Spreadsheet field name
closes #599
> change "Site File" -> "Area of Interest Boundary File"

- templates/_form_macros.html
- templates/order-form.html
apparently google spreadsheets doesn't like parenthesis :no_good:
> Fix order form spreadsheet

- content/markdown/news/2015-08-11-lidar-data-release-austin-capcog-2012.md
When writing "City, State" a comma should also come after the state if the sentence continues. cc @ThorTheDestroyer
> Add comma after Texas

- scss/partials/_gio-page.scss
- templates/gio.html
- templates/partials/gio-meeting.html
Closes #433 
@christoball please review
> add GIO mailing list sign-up

- static/js/data-download/partials/results.html
ref: https://github.com/TNRIS/data-download/issues/37
> Make historical imagery search result message more clear

- content/markdown/2015-gis-forum/agenda.md
> agenda name change, closes #628

- static/js/data-download/services/DataService.js
> reverse sort CCMs on data download page

- templates/order-form.html
also made some slight language improvements
> specify external drives only, closes #639

- templates/order-form.html
@wilsaj  - Please review and merge if good
> standardize Lidar capitalization, fixes #640

- content/markdown/2015-statewide-orthoimagery-project.md
Weekly report and map emailed to Chris.
> ortho-update-oct-16

- content/markdown/maps-and-data.md
- content/markdown/maps-and-data/custom-maps.md
- content/markdown/maps-and-data/data-and-mapping-solutions.md
- content/markdown/maps-and-data/online-mapping-services.md
- content/markdown/maps-and-data/research-and-distribution.md
- scss/partials/_maps-and-data.scss
- templates/maps-and-data.html
- templates/order-form.html
> Cleanup maps and data pages rebase

- scss/partials/_base.scss
- templates/partials/gio-meeting.html
- templates/partials/google/google-update.html
> incorporating felicia's edits for gio/google

- gulpfile.js
- fixes favicon (closes #664)
- fixes robots.txt too
> cp files in root of static dir to the root of dist dir

- gulpfile.js
currently only `short_description` and `description` but it's easy to
enable on others when needed
closes #724
> run data catalog fields through markdown renderer

- content/markdown/news/2015-11-22-glo-tceq-tpwd-datasets-expand-data-catalog.md
@christoball can you review? Feel free to merge and publish or make any changes.
> Copy edits grammar catalog expansion article

- content/markdown/news/2015-11-30-city-of-georgetown-2015-aerial-imagery-now-available.md
Added Surdex Corp. hyperlink edit.
> surdex-hyperlink

- templates/data-catalog-entry.html
- templates/wms.html
all of the catalog CSV entries need to be updated to include full protocol url `http://`
coordinate with @mitchellryant on getting that done and deployed
> don't insert protocol for WMS pop_links - these s/b part of the catalog csv

- gulpfile.js
and make it easy to add additional metadata fields in the future
> run 'updates' content metadata field through markdown renderer

- content/markdown/2015-statewide-orthoimagery-project.md
- templates/partials/2015-ortho/top-update.html
No new vendor report or maps with this update.
> ortho-update-jan-01

- templates/order-form.html
- templates/twdb-order-form.html
> Ftp to digital download

- gulpfile.js
- templates/data-catalog-entry.html
NOTE: wait for all tasks in #749 to be cleared before merging
closes #749
> add tile index and supplemental reports to catalog entry pages

- gulpfile.js
- templates/index.html
- templates/partials/highlights.html
- templates/updates.html
> Combined updates feed

- templates/2016-lidar-acquisition-project.html
Adding a notice to vendors not use lidar project contact form for bid inquiries.
@ThorTheDestroyer @geochik @KCMack Does this language look alright?
https://beta.tnris.org/2016-lidar-acquisition-project/#contact-pm
> adding vendor notice to Lidar contact

- content/markdown/georodeo/index.md
temp fix for #828, but we still need a proper server-side redirect
> client-side redirect for /georodeo -> /georodeo/2016/

- scss/partials/_georodeo.scss
> fixing georodeo banner in own branch

- content/markdown/2015-statewide-orthoimagery-project.md
Weekly ortho update. No report or maps to update.
> ortho-update-mar-04

- templates/partials/gio-meeting.html
Adding address. My rookie tendencies produce little confidence. Please review the code.
> add meeting location 2016-03-15

- content/markdown/texas-google-imagery.md
Content updates to correct pilot end date and transition to Google Cloud Platform.
@christoball  Please review line 26. The word UPDATE should be bolded or red or both to emphasize update. Maybe a quick lesson on how to make that happen is in order. :+1: 
Thank you!
> 20160418-Google-content-updates-FDR

- templates/partials/highlights.html
> updating highlights link to new forum page

- content/training.csv
> closing course, resolves #906

- content/markdown/geographic-information-office/2016-01-20-notes-texas-gis-community-meeting-2nd-quarter-2016.md
- content/markdown/geographic-information-office/2016-04-04-agenda-2016-2nd-quarter-texas-gis-community-meeting.md
- content/markdown/geographic-information-office/2016-04-20-notes-texas-gis-community-meeting-2nd-quarter-2016.md
- templates/index.html
New page for 2016 2nd qtr GIS Community meeting notes.
@christoball Is this not directly under the master branch? Not sure what happened here.
Also, need to upload PPTs to Speaker Deck and Link. Will send link separately.
@gmullins @ThorTheDestroyer Can you please review the notes and edit at will? Thanks!
> 20160428-2nd-qtr-gis-community-mtg-notes.md

- content/markdown/georodeo/2016/index.md
> adding andy dearing abstract

- templates/2016-lidar-acquisition-project.html
adjusted embeded map link and funding status for SARA AOI
> Lidar project page update

- content/markdown/stratmap/stratmap-contract.md
- templates/stratmap/contract-vendors.html
Updated page based on Linda Hart's,DIR, suggestions.
@christoball Can you link the StratMap@twdb.texas.gov email in the body?
Also, Geo-Comm and Tesselations are now active and should not be greyed out. I'll get you the links.
> gm edits per linda hart

- content/markdown/geographic-information-office/gis-solutions-group/meeting-notes/2016-06-15-notes-may-2016-dcs-gis-solutions-group.md
- templates/partials/gio-sub-dcs.html
- templates/partials/gis-solutions-meeting.html
> adding may 2016 DCS group notes

- content/markdown/texas-gis-forum/2016/training.md
- templates/events/texas-gis-forum/2016/2016-forum-training-entry.html
- templates/events/texas-gis-forum/2016/2016-forum-training.html
> updating 2016 forum training dates

- content/markdown/news/2016-04-11-robert-ballard-discoverer-titanic-wreck-keynote-2016-gis-forum.md
> copy edit in ballard article

- content/markdown/high-priority-imagery-data-sets.md
- content/markdown/stratmap/orthoimagery.md
- content/markdown/stratmap/stratmap-contracts.md
- content/training.csv
- templates/index.html
- templates/partials/navbar.html
- templates/stratmap/contract-vendors.html
- templates/stratmap/main-content.html
- templates/stratmap/nav.html
resolves #1010 resolves #1010 
Also resolves @gmullins vendor updates and name change to 'Stratmap Contracts' in #911
> Stratmap headings

- content/markdown/news/2016-06-30-tnris-jobs-seeking-two-new-geo-developers.md
- static/documents/jobs/16-54.pdf
Ive created a draft of the job posting article. Please review for errors and make suggestions
https://deploy.tnris.org/api/v1/preview/e424b9dd8523ee265ee920f7c82411490ec4acb1/news/2016-06-30/tnris-jobs-seeking-two-new-geo-developers/
front page blurb
> first draft of jobs posting

- templates/partials/gio-meeting.html
@christoball 
I know you are on vacation, but if you happen to get to a computer, is there a chance you can make this update happen?
> Update GIO Meeting Time and Place

- templates/partials/gis-solutions-meeting.html
> changing DSG meeting time

- content/markdown/geographic-information-office/gis-solutions-group/meeting-notes/2016-07-21-notes-june-2016-dcs-gis-solutions-group.md
- templates/partials/gis-solutions-meeting.html
> adding june dcs notes

- content/markdown/news/2016-07-26-san-antonio-river-authority-2015-2016-aerial-imagery-now-available.md
- templates/stratmap/contract-vendors.html
resolves #1051 resolves #1062 
@gmullins is it ok to close #898 ?
> fixing sara page and updating strat vendor

- content/markdown/geographic-information-office/2016-07-12-notes-texas-gis-community-meeting-3rd-quarter
- content/markdown/geographic-information-office/2016-07-12-notes-texas-gis-community-meeting-3rd-quarter-2016.md
@christoball These notes are almost ready to go. There are a couple of places where state agency logos are missing and the speakerdeck links should be updated with the new slide decks. Slide decks will be emailed to you.
> final-3rdqtr-gio-mtg-notes-20160819

- templates/2016-lidar-acquisition-project.html
Fixing typo 'acquistion' in intro
> fixing typo

- templates/events/texas-gis-forum/2016/agenda-2016.html
- templates/events/texas-gis-forum/2016/welcome.html
> adding holl to both days, fixing keynote time on welcome

- templates/2016-lidar-acquisition-project.html
updated embeded map link
@christoball
> Updated East Texas Map graphic

- content/markdown/texas-gis-forum/2016/agenda.md
- generate-webpack-config.js
- static/js/2015forum.js
- templates/events/texas-gis-forum/2016/agenda-2016.html
- templates/events/texas-gis-forum/2016/main.html
> Forum javascript

- templates/stratmap/contract-vendors.html
> updating stratmap contracts page
